<?php


namespace Blog\Controller;


use Zend\Mvc\Controller\AbstractActionController;

class ListController extends AbstractActionController
{
    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }
}