<?php

$title = 'Delete user';
$url = $this->url('user', ['action' => 'delete', 'uid' => $uid]);

$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($user->uid) ?>" with
    "<?= $this->escapeHtml($user->email) ?>"?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="uid" value="<?= $uid ?>">
        <input type="submit" class="btn-danger" name="delete" value="Yes">
        <input type="submit" class="btn-success" name="delete" value="No">
    </div>
</form>
