<?php
    $title = 'Edit user ' . $uid;
    $this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>
<?php
    $userId = $form->get('uid');
    $userId->setAttribute('class', 'form-control');
    $userId->setAttribute('placeholder', 'User Id');

    $password = $form->get('psw');
    $password->setAttribute('class', 'form-control');
    $password->setAttribute('placeholder', 'Password');

    $email = $form->get('email');
    $email->setAttribute('class', 'form-control');
    $email->setAttribute('placeholder', 'Email Address');

    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');

    $form->setAttribute('action', $this->url('user', [
            'action' => 'edit',
            'uid' => $uid,
    ]));
    $form->prepare();

    echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($userId) ?>
    <?= $this->formElement($userId) ?>
    <?= $this->formElementErrors()->render($userId, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
</div>

<?php
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
